- .github/workflows/build.yml
- common/src/main/java/com/turikhay/mc/mapmodcompanion/Handler.java
- gradle.properties
- spigot/build.gradle
- spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/MapModCompanion.java
- spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/ProtocolLib.java
In order to handle special cases like #8 we need to know player's protocol version
> Add ProtocolLib

- README.md
- spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/LevelIdHandler.java
- spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/PrefixedIdRequest.java
- spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/ProtocolVersion.java
- spigot/src/test/java/com/turikhay/mc/mapmodcompanion/spigot/PrefixedIdRequestParserTest.java
> Fix Forge VoxelMap on 1.13.2 - 1.16.3

- common/src/main/java/com/turikhay/mc/mapmodcompanion/FileChangeWatchdog.java
- common/src/main/java/com/turikhay/mc/mapmodcompanion/Handler.java
- common/src/main/java/com/turikhay/mc/mapmodcompanion/ILogger.java
- common/src/main/java/com/turikhay/mc/mapmodcompanion/IdBlender.java
- common/src/test/java/IdBlenderTest.java
- packages/single/build.gradle
- settings.gradle
- velocity/build.gradle
- velocity/log4j2-debug.xml
- velocity/src/main/java/com/turikhay/mc/mapmodcompanion/velocity/Channels.java
- velocity/src/main/java/com/turikhay/mc/mapmodcompanion/velocity/MapModCompanion.java
- velocity/src/main/java/com/turikhay/mc/mapmodcompanion/velocity/MessageHandler.java
- velocity/src/main/java/com/turikhay/mc/mapmodcompanion/velocity/package-info.java
- velocity/src/main/resources/config_velocity.toml
> Velocity support

- bungee/src/main/java/com/turikhay/mc/mapmodcompanion/bungee/PacketHandler.java
- velocity/src/main/java/com/turikhay/mc/mapmodcompanion/velocity/MessageHandler.java
> Stop "Received possibly malformed packet" flood

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/PluginDescriptor.kt
- bungee/build.gradle.kts
- gradle/libs.versions.toml
- spigot/build.gradle.kts
- velocity/build.gradle.kts
We don't use its features enough.
Spigradle seems to be unmaintained and might become a burden in the near future.
> Remove Spigradle

- README.md
- spigot/build.gradle.kts
> Add Folia support

- README.md
Thanks to https://github.com/badges/shields/pull/9800 being merged, I can now add Hangar badge.
> Hangar badge

- buildSrc/src/main/kotlin/PlatformReadme.kt
- packages/single/build.gradle.kts
#83 wasn't successful. Will try to use lazy property instead of a task.
> Fix platform pages updating

- .github/workflows/update-pages.yml
We use incorrect task to upload pages to Hangar
> Fix hangar pages upload

- README.md
Personally, I prefer Modrinth over CurseForge.
> Update mod links

- README.md
I want badges to appear on Hangar and Modrinth pages.
> Hide platform badges

- .github/workflows/update-pages.yml
> Upgrade setup-gradle in update-pages.yml

- .github/workflows/build.yml
- .github/workflows/update-pages.yml
See https://github.com/gradle/wrapper-validation-action/issues/160
> Upgrade gradle/wrapper-validation-action to v2

- README.md
With #62 closed, I can update the support table to reflect latest changes.
> Update support table

- .github/workflows/update-gradle.yml
[See discussion](https://github.com/orgs/community/discussions/27028#discussioncomment-6031792)
> Re-run CI after gradle-update is triggered

- .github/workflows/update-gradle.yml
> Add repo token back

- .github/FUNDING.yml
See [[1]](https://github.blog/changelog/2024-03-14-sponsors-now-supports-polar-and-buy-me-a-coffee-as-funding-platform-options/)
> Buy Me a Coffee is now supported

- .github/workflows/hangar.yml
- .github/workflows/modrinth.yml
Platform uploads have been broken all this time, huh?
> Fix uploads

- .github/workflows/build.yml
- .github/workflows/hangar.yml
- .github/workflows/modrinth.yml
Continuation of https://github.com/turikhay/MapModCompanion/pull/119
Environment variables [are not passed to called workflows](https://stackoverflow.com/questions/73305126/passing-env-variable-inputs-to-a-reusable-workflow), huh...
> Fix uploads, part 2

- .github/workflows/build.yml
- .github/workflows/hangar.yml
- .github/workflows/modrinth.yml
> Fix uploads, part 3

- .github/workflows/build.yml
- .github/workflows/hangar.yml
- .github/workflows/modrinth.yml
- packages/single/build.gradle.kts
> Fix uploads, part 4

- packages/single/build.gradle.kts
Basically "Fix uploads, part 5" #122
> Fix Modrinth upload

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/PlatformReadme.kt
- packages/single/build.gradle.kts
* Don't update README on release (it's done on every commit to `main` anyway)
* Migrate to using a plugin instead of calling a function inside the provider
> Improve platform README updating

- README.md
It is abandoned and probably no longer works.
> Remove MinimapServer from the Alternatives

- spigot/build.gradle.kts
Includes reverted changes from #134 
* Rearranges fields to match the order found in [the docs](https://docs.papermc.io/paper/dev/plugin-yml)
* Adds new fields: `description`, `website`
> Improve plugin.yml

- tests_e2e/run.py
Folia tests were failing recently.
See https://github.com/itzg/docker-minecraft-server/issues/2992
> Fix Folia tests
