turikhay/MapModCompanion

.github/workflows/e2e_minmax.yml
.github/workflows/e2e_notable.yml
README.md

Partially reverts #24, because 30+ tests fail too often.

Run E2E tests against "notable" versions

---

spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/XaeroHandler.java

In order to bring Folia #72, I'm gonna try to migrate Xaero to its own scheduler.
According to https://github.com/turikhay/MapModCompanion/issues/72#issuecomment-1885608450, in order to use modern schedulers provided by the server, we'll need to depend on `folia-api`, which is only available on Java 17.
We could split the Spigot plugin into two separate projects that use different Java versions, but this is just simpler. This might work.

Migrate Xaero to its own scheduler

---

spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/BukkitScheduler.java
spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/FoliaSupport.java
spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/MapModCompanion.java
spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/PluginScheduler.java
spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/SingleThreadScheduler.java

Closes #76 
#74 wasn't enough to make plugin fully compatible with Folia. Let's try to use our own thread to load/unload the plugin.

Use SingleThreadScheduler in Folia

---

gradle/libs.versions.toml

Add explicit jackson-core dependency. We implicitly use it in the `buildSrc`:
https://github.com/turikhay/MapModCompanion/blob/7e13a5c6c6b373d6fa85209dfce0c42364bd34ea/buildSrc/build.gradle.kts#L13-L17
With this small "hack" in place, dependabot will be able to upgrade this dependency automatically. I expect all jackson projects update simultaneously.

Add explicit jackson dependency

---

.github/workflows/build.yml

> The gradle-build-action has support for submitting a [GitHub Dependency Graph](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph) snapshot via the [GitHub Dependency Submission API](https://docs.github.com/en/rest/dependency-graph/dependency-submission?apiVersion=2022-11-28).
[[1]](https://github.com/gradle/gradle-build-action/tree/42452daeb5b454a76f686a8e4de8234afd7b1f44#github-dependency-graph-support)

Submit Dependency Graph

---

.github/workflows/update-pages.yml

`Run the build` should be `Run tasks`

Rename the job left from copy-pasting

---

.github/workflows/build.yml

`gradle/actions/setup-gradle` replaces `gradle-build-action`
See: [[1]](https://github.com/gradle/actions/blob/5b6457b09bea73ff064cfca8e850c64701ea9cb8/README.md#the-setup-gradle-action) [[2]](https://github.com/gradle/gradle-build-action/blob/ef85c4ed42c6bd3e2d9deb8edcba57e41360968b/README.md)

Upgrade gradle-build-action@v2 to gradle/actions/setup-gradle@v3

---

.github/workflows/update-gradle.yml

[According to the docs](https://github.com/gradle-update/update-gradle-wrapper-action/blob/f0a708cf2ee01e34c7092100e20cf3e2f3af4e1c/README.md#usage), we don't actually need passing GitHub token.

remove repo token

---

gradle/libs.versions.toml

This will bring Gradle 8.6 support.
0.1.1 fails, see [corresponding action run](https://github.com/turikhay/MapModCompanion/actions/runs/7769592482):
```
BUILD FAILED in 1m 6s
10 actionable tasks: 10 executed
Error: ❌ FAILURE: Build failed with an exception.
* Where:
Build file '/home/runner/work/MapModCompanion/MapModCompanion/packages/single/build.gradle.kts' line: 59
* What went wrong:
Could not create domain object 'plugin' (HangarPublicationImpl)
> Could not create an instance of type io.papermc.hangarpublishplugin.internal.model.HangarPublicationImpl.
> Could not create an instance of type io.papermc.hangarpublishplugin.internal.model.PlatformContainerImpl.
> Could not generate a decorated class for type PlatformContainerImpl.
> Cannot have abstract method …
```

Upgrade Hangar plugin to 0.1.2

---

buildSrc/src/main/kotlin/ProjectExt.kt
buildSrc/src/main/kotlin/java-shadow.gradle.kts
packages/single/build.gradle.kts
velocity/build.gradle.kts

Closes #117 
New Paper remapper doesn't like duplicate entries in the plugin jar. I came up with a simple and a bit naive solution: we take output of `shadowJar` and create a new jar with `DuplicatesStrategy.EXCLUDE` set, and then replace the original one.
EDIT: We should avoid replacing original jar; it's better to just use `dedupShadowJar` output instead

Deduplicate output jar files

---

packages/single/build.gradle.kts

I've used Kotlin `lazy` properties for "heavy" tasks but it's better to use native Gradle providers.

Migrate to lazy providers

---

packages/single/build.gradle.kts

Paper is not only available for major releases like 1.20, but also for minor ones (1.20.x). We should reflect that when uploading our artifacts to Hangar.

Hangar: use latest Paper version

---

spigot/build.gradle.kts

`[19:24:31] [Server thread/WARN]: Legacy plugin MapModCompanion v0.10.0-beta.6 does not specify an api-version.`

fix api-version

---

spigot/build.gradle.kts

Follow-up to #131
I wasn't paying attention to [the actual/correct field names](https://docs.papermc.io/paper/dev/plugin-yml) when I removed Spigradle support (#73): `softDepends` should be `softdepend`

Fix softdepend

---

spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/MapModCompanion.java

Adjust log levels for non-default configurations

---

.github/workflows/e2e_all.yml
.github/workflows/e2e_notable.yml
tests_e2e/run.py

- Requires specifying Java version for each testable version (was defaulting to Java 17 before)
- Displays server logs alongside bot output
- Debugging is only affected by setting the debug level. Before it was set by `ACTIONS_STEP_DEBUG` env var, which was never used.
The latest release 1.21.3 is not yet supported by [node-minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol), so it's not tested by the bot.
No Folia support for [1.20.5](https://papermc.io/api/v2/projects/folia/versions/1.20.5), 1.21 - [1.21.3](https://papermc.io/api/v2/projects/folia/versions/1.21.3) neither.

Support testing on 1.20.6 - 1.21.3

---

.github/workflows/e2e_all.yml
.github/workflows/e2e_notable.yml
.github/workflows/e2e_test.yml
tests_e2e/README.md
tests_e2e/run.py

docker-minecraft-server supports [different backend servers](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/server-types/paper/).
This PR makes it easier to select between these. It's also making GitHub Actions look cleaner: there are no more ambiguous `false` and `true` action variants.

Make server type (Paper, Folia) selectable

---

.gitignore

create-pull-requests creates invalid PRs (#170, #171) because Gradle dependency graph files are not ignored

Ignore dependency-graph-reports

---

gradle/libs.versions.toml

[bstats 3.1.0](https://github.com/Bastian/bstats-metrics/releases/tag/v3.1.0) brings Folia support

Bump bstats to support Folia

---

spigot/build.gradle.kts

Related to #203
See https://github.com/dmulloy2/ProtocolLib/issues/3373
[Recent builds](https://github.com/turikhay/MapModCompanion/actions/runs/17378639437/job/49330666057) have been failing with this error:
```
> Could not resolve com.comphenix.protocol:ProtocolLib:5.3.0.
Required by:
project ':spigot'
> Could not resolve com.comphenix.protocol:ProtocolLib:5.3.0.
> Could not get resource 'https://repo.dmulloy2.net/repository/public/com/comphenix/protocol/ProtocolLib/5.3.0/ProtocolLib-5.3.0.pom'.
> Could not GET 'https://repo.dmulloy2.net/repository/public/com/comphenix/protocol/ProtocolLib/5.3.0/ProtocolLib-5.3.0.pom'. Received status code 403 from server: Forbidden
```
Since ProtocolLib is now published on Maven Central under a new group ID (`net.dmulloy2` instead of …

Use ProtocolLib from Maven Central

---

README.md
tests_e2e/run.py

* Add 1.21.9 to E2E tests (in manual-only mode)
* Update compatibility table

Confirm 1.21.9 support
